# Generated by Django 4.2.13 on 2024-08-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorymodel_slug_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='slug_title',
            new_name='sub_slugify1',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='sub_slugify2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
