# Generated by Django 4.2.13 on 2024-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_slug_title_categorymodel_sub_slugify1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='main.booksmodel'),
        ),
    ]
