# Generated by Django 4.2.13 on 2024-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to='main.booksmodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='main.booksmodel'),
        ),
    ]
