# Generated by Django 4.2.13 on 2024-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_basket_alter_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed',
            field=models.ManyToManyField(blank=True, max_length=50, related_name='viewed', to='main.booksmodel'),
        ),
    ]
