# Generated by Django 5.1.6 on 2025-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_booksmodel_author_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='author_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='author_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='cover_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='cover_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='info_txt_en',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='info_txt_ru',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='interpreter_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='interpreter_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='publishing_brand_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='publishing_brand_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='publishing_house_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='publishing_house_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='series_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='series_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
