# Generated by Django 5.1.6 on 2025-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_booksmodel_author_en_booksmodel_author_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='img_local',
            field=models.FileField(default='', upload_to='cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='img',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
