# Generated by Django 5.1.6 on 2025-03-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_booksmodel_img_local_alter_booksmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='id_book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
