# Generated by Django 5.1.6 on 2025-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_booksmodel_creator_alter_booksmodel_id_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.categorymodel'),
        ),
    ]
