# Generated by Django 5.1.6 on 2025-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_booksmodel_age_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='publishing',
            field=models.BooleanField(default=False),
        ),
    ]
