# Generated by Django 5.1.6 on 2025-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_booksmodel_img_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='img_local',
            field=models.FileField(blank=True, upload_to='cover'),
        ),
    ]
