# Generated by Django 5.1.6 on 2025-03-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_booksmodel_img_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='num_score',
        ),
        migrations.RemoveField(
            model_name='booksmodel',
            name='score',
        ),
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='category',
            field=models.ManyToManyField(to='main.categorymodel'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='cover_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='cover_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='cover_type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='num_page',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='publishing_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='publishing_brand_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='publishing_brand_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='weight',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='year_of_publishing',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
