# Generated by Django 5.1.6 on 2025-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_booksmodel_num_score_remove_booksmodel_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='year_of_publishing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
