# Generated by Django 5.1.6 on 2025-03-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_booksmodel_id_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.booksmodel'),
        ),
    ]
