# Generated by Django 5.2.1 on 2025-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_user_is_verified_user_verification_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
