# Generated by Django 5.2.1 on 2025-07-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_user_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
