# Generated by Django 5.2.1 on 2025-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_user_products_viewed_user_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewed',
            options={'ordering': ['-date_viewed']},
        ),
    ]
