# Generated by Django 5.2.1 on 2025-07-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_viewed_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewed',
            new_name='ViewedModel',
        ),
    ]
