# Generated by Django 5.2.1 on 2025-07-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_viewedmodel_unique_together_remove_user_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='viewedmodel',
            name='book',
            field=models.ManyToManyField(related_name='book_viewed', to='main.booksmodel'),
        ),
    ]
