# Generated by Django 5.2.1 on 2025-07-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_viewedmodel_book_viewedmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='viewedmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_viewed', to='main.booksmodel'),
        ),
    ]
