# Generated by Django 5.2.1 on 2025-07-18 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_viewedmodel_book_viewedmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Verification UUID'),
        ),
    ]
